export type DetailItem = { name: string; note: string; tag?: string; map?: string };
export type Destination = {
  id: string; name: string; region: string; category: string; mood: string; days: string; budget: number;
  altitude: string; intro: string; history: string; bestFor: string[]; color: string; coordinates: string;
  activities: DetailItem[]; eat: DetailItem[]; stay: DetailItem[]; transport: DetailItem[]; tip: string; caution?: string;
};

const m = (name: string, note: string, tag?: string): DetailItem => ({ name, note, tag, map: name });

export const destinations: Destination[] = [
  {
    id:"antigua",name:"Antigua",region:"Sacatepéquez",category:"Culture",mood:"Courtyards & volcano light",days:"3 days",budget:2,altitude:"1,545 m",coordinates:"14.5586° N",
    intro:"Guatemala’s walkable colonial heart: baroque ruins, coffee courtyards and volcano views in every direction.",
    history:"Founded in 1543 as Santiago de los Caballeros, Antigua was the Spanish colonial capital until earthquakes prompted the move to present-day Guatemala City in 1773. Its preserved grid, churches and ruins are now UNESCO-listed.",
    bestFor:["Architecture","Food","Coffee","Day hikes"],color:"coral",
    activities:[m("Convento de las Capuchinas","Explore the unusual circular novices’ tower and the vast Fuente de los Pescados.","1–1.5 hr"),m("Iglesia de La Merced","See the intricate yellow baroque façade and convent fountain.","45 min"),m("Cerro de la Cruz","Walk up in daylight for the classic city-and-Volcán de Agua view.","1 hr"),m("Casa Santo Domingo museums","Six small collections mixing Maya, colonial and contemporary works.","2 hr"),m("Arco de Santa Catalina","Best early, before the street fills; continue north toward La Merced.","20 min"),m("Caoba Farms","Tour an organic farm, then stay for a garden lunch.","2 hr")],
    eat:[m("Caoba Farms","Farm-to-table lunches and wood-fired bakery just south of town.","Fresh"),m("Mesón Panza Verde","Long-running fine-dining room for a special evening.","Splurge"),m("Mercado de Antigua","Go for tostadas, fruit and everyday Guatemalan cooking.","Local"),m("Rincón Típico","Simple set lunches and roast chicken in a courtyard.","Value")],
    stay:[m("Mesón Panza Verde","Historic boutique stay on the quieter south side.","Boutique"),m("Good Hotel Antigua","Social-impact design hotel near the center.","Midrange"),m("Casa Santo Domingo","Museum-like historic property among monastery ruins.","Splurge")],
    transport:[m("From Guatemala City airport","Pre-booked shuttle or vetted driver; typically 1–2.5 hours depending on traffic.","Road"),m("To Lake Atitlán","Shared shuttle to Panajachel; allow 3–4 hours.","Shuttle"),m("Around Antigua","Walk by day; use vetted taxis or rideshare after dark.","Local")],tip:"Start at Capuchinas at opening, cross the center slowly, and save Cerro de la Cruz for clear late-afternoon light."
  },
  {
    id:"atitlan",name:"Lake Atitlán",region:"Sololá",category:"Nature",mood:"Village-to-village lake days",days:"4 days",budget:2,altitude:"1,562 m",coordinates:"14.6907° N",
    intro:"A volcanic caldera where each lakeside town has its own pace, craft traditions and view.",history:"Atitlán has been home to Tz’utujil and Kaqchikel Maya communities for centuries. The lake fills a volcanic basin framed by the San Pedro, Tolimán and Atitlán volcanoes.",bestFor:["Slow travel","Maya culture","Paddling","Textiles"],color:"aqua",
    activities:[m("San Juan La Laguna","Visit women-led weaving and natural-dye cooperatives; ask before photographing.","Half day"),m("Santiago Atitlán","Learn about Tz’utujil traditions and visit Maximón with a respectful local guide.","Half day"),m("Santa Catarina Palopó","Painted façades, ceramics and a quieter eastern-lake perspective.","2–3 hr"),m("Sunrise paddle from Santa Cruz","Calm water and volcano silhouettes before boat traffic begins.","2 hr"),m("Indian Nose / Rostro Maya","Guided pre-dawn hike from Santa Clara; confirm current trail conditions.","Half day"),m("Reserva Natural Atitlán","Hanging bridges, forest paths and butterfly reserve near Panajachel.","2–3 hr")],
    eat:[m("Atitlán Rest y Café","Family-run lakeside Guatemalan cooking in Panajachel.","Local"),m("Kinnik at Casa Palopó","Waterside destination dining near Santa Catarina.","Splurge"),m("San Juan cooperatives","Look for community-run cafés and locally grown coffee.","Community")],stay:[m("La Casa del Mundo","Cliffside Jaibalito retreat reached by boat or foot.","Iconic"),m("Casa Palopó","Art-filled Relais & Châteaux stay above Santa Catarina.","Splurge"),m("Hotel Atitlán","Gardens and easy access from Panajachel.","Classic"),m("Sababa Resort","Lakeside option near San Pedro’s social scene.","Social")],
    transport:[m("From Antigua","Shared shuttle to Panajachel, normally 3–4 hours.","Shuttle"),m("Public lanchas","Frequent daytime boats connect major towns; confirm the last departure locally.","Boat"),m("Lake crossings","Sit toward the back on rough afternoons and protect electronics from spray.","Tip")],tip:"Pick one home base, then make two deliberate village day trips. Constantly changing hotels wastes the lake’s best hours."
  },
  {
    id:"peten",name:"Flores, Tikal & Yaxhá",region:"Petén",category:"History",mood:"Temples above the canopy",days:"3 days",budget:3,altitude:"128 m",coordinates:"16.9300° N",
    intro:"A compact island base for Guatemala’s monumental Maya cities and wildlife-rich northern jungle.",history:"Tikal grew into one of the ancient Maya world’s most powerful cities, flourishing especially from the 3rd to 9th centuries. Nearby Yaxhá developed between two lakes and rewards visitors with an atmospheric sunset setting.",bestFor:["Archaeology","Wildlife","Sunrise","Photography"],color:"jungle",
    activities:[m("Tikal National Park","Allow a full day; use a licensed guide to read the city beyond its tallest temples.","Full day"),m("Yaxhá sunset","Climb Temple 216 before closing for lake-and-jungle light.","Half day"),m("Flores island loop","Walk the colorful waterfront, lanes and central plaza at golden hour.","1–2 hr"),m("Ixpanpajul","Forest canopy walks and hanging bridges outside Flores.","Half day"),m("Uaxactún","Smaller Maya site and living forest community north of Tikal.","Full day")],
    eat:[m("Maple & Tocino","Creative brunch and comfort food on Flores island.","Casual"),m("Raíces Bar & Grill","Lakefront tables for grilled dishes and sunset.","View"),m("Street-food waterfront","Try dobladas and fresh fruit where locals gather in the evening.","Local")],stay:[m("Hotel Isla de Flores","Classic island location close to restaurants.","Central"),m("La Lancha","Jungle lodge on Lake Petén Itzá outside town.","Retreat"),m("Bolontiku","Quiet boutique lake resort reached west of Flores.","Splurge")],
    transport:[m("From Guatemala City","A short domestic flight to Flores saves a full travel day.","Flight"),m("To Tikal","Pre-booked shared shuttle or tour; roughly 1.5 hours each way.","Road"),m("To Belize","Use a reputable international shuttle and verify current border requirements.","Border")],tip:"Pair Tikal with Yaxhá rather than repeating Tikal at sunrise and sunset. The two cities feel genuinely different.",caution:"Petén is hot and mosquito-prone. Carry water, repellent and sun protection; ask a travel clinician about malaria prevention."
  },
  {
    id:"semuc",name:"Semuc Champey",region:"Alta Verapaz",category:"Adventure",mood:"Turquoise water, deep green",days:"2–3 days",budget:2,altitude:"350 m",coordinates:"15.5333° N",
    intro:"A remote limestone bridge covered in stepped pools, reached through the lush Q’eqchi’ Maya highlands.",history:"The Cahabón River disappears beneath a natural limestone bridge while calm pools form above it—Semuc Champey means ‘where the river hides under the stones’ in Q’eqchi’.",bestFor:["Swimming","Jungle","Caves","Remote stays"],color:"mint",
    activities:[m("El Mirador trail","Steep, humid climb for the signature view over the pools.","1.5 hr"),m("Semuc pools","Swim only in designated sections and keep valuables minimal.","2 hr"),m("K’an Ba cave","Candlelit water cave; choose a safety-conscious operator and closed-toe footwear.","1.5 hr"),m("Lanquin town","Market, church and a slower look at local life beyond the lodges.","1–2 hr")],eat:[m("Zephyr lodge restaurant","Reliable international and Guatemalan dishes with valley views.","Social"),m("Lanquin comedor","Choose a busy local comedor for caldo, eggs and tortillas.","Local")],stay:[m("Utopia Eco Hotel","Jungle property along the road toward Semuc.","Nature"),m("Zephyr Lodge","Social hillside stay with broad valley views.","Social"),m("El Retiro","Long-running riverside option near Lanquín.","Value")],transport:[m("From Antigua","Tourist shuttle; expect a long, often 9–11 hour road day.","Shuttle"),m("Lanquín to Semuc","Local 4x4 transport on a rough road, roughly 45–60 minutes.","4x4")],tip:"Stay two nights minimum. Arrive, sleep, spend one full early day at the monument, and leave the next morning.",caution:"Alta Verapaz is a malaria-risk department per CDC guidance; discuss your exact itinerary with a clinician."
  },
  {
    id:"acatenango",name:"Acatenango",region:"Chimaltenango",category:"Adventure",mood:"A night above the clouds",days:"2 days",budget:3,altitude:"3,976 m",coordinates:"14.5011° N",
    intro:"A serious overnight volcano trek with expansive highland views and a front-row—but safely distant—view of Fuego.",history:"Acatenango is a stratovolcano complex paired visually with active Fuego. Its elevation, cold and loose volcanic terrain make this a demanding mountain rather than a casual excursion.",bestFor:["Trekking","Camping","Sunrise","Challenge"],color:"slate",
    activities:[m("Basecamp sunset","Layer up before the temperature drops and keep your headlamp accessible.","Evening"),m("Summit sunrise","Optional pre-dawn ascent; assess altitude symptoms honestly.","3–4 hr"),m("La Soledad trail","The standard guided route climbs through farms, cloud forest and alpine terrain.","5–7 hr up")],eat:[m("Operator camp meals","Confirm drinking water, portions and dietary needs before booking.","Included"),m("Antigua recovery meal","Plan a substantial meal and flexible morning after descending.","After hike")],stay:[m("Guided basecamp","Choose an operator with quality tents, sleeping bags and emergency plans.","Required"),m("Antigua pre/post night","Sleep in Antigua on both sides of the trek; avoid tight onward connections.","Smart plan")],transport:[m("From Antigua","Licensed operators usually include transfers to La Soledad.","Tour"),m("Trail access","Go with an authorized local guide and register as required locally.","Guide")],tip:"Compare equipment and safety protocols—not only price. Rent genuinely warm layers and carry more water than you think.",caution:"Conditions and access change with Fuego activity. Check CONRED/INSIVUMEH notices and never approach Fuego itself."
  },
  {
    id:"rio-dulce",name:"Río Dulce & Lívingston",region:"Izabal",category:"Nature",mood:"River canyon to Caribbean",days:"3 days",budget:2,altitude:"Sea level",coordinates:"15.6589° N",
    intro:"A boat journey through hot springs and jungle walls to Guatemala’s Garifuna Caribbean coast.",history:"The Río Dulce corridor connects Lake Izabal with the Caribbean. Castillo de San Felipe guarded the colonial trade route; Lívingston remains a distinctive Garifuna, Q’eqchi’ and Afro-Caribbean cultural meeting point.",bestFor:["Boats","Garifuna culture","Birding","Seafood"],color:"blue",
    activities:[m("Río Dulce canyon boat","Take the morning public or private boat between the town and Lívingston.","2–3 hr"),m("Castillo de San Felipe","Compact lakeside Spanish fort near Fronteras.","1–2 hr"),m("Finca Paraíso","Warm waterfall and cool river near Lake Izabal.","Half day"),m("Siete Altares","Coastal pools reached with a local guide from Lívingston.","Half day"),m("Playa Blanca","Boat-access beach often paired with Siete Altares.","Half day")],eat:[m("Tapado in Lívingston","Garifuna coconut-seafood stew; order from a busy local kitchen.","Signature"),m("Casa Nostra","Riverfront Italian-Caribbean cooking in Lívingston.","Dinner")],stay:[m("Tortugal Boutique River Lodge","Marina lodge reached by boat near Río Dulce.","River"),m("Hotel Villa Caribe","Established waterfront base in Lívingston.","Central")],transport:[m("From Guatemala City","Daytime bus or private shuttle; allow most of a day.","Road"),m("To Lívingston","Boat is the only practical arrival; morning rides are usually smoother.","Boat"),m("To Honduras/Belize","Use established international boat/shuttle services and verify border schedules.","Border")],tip:"Travel east by road, sleep on the river, then take the canyon boat to Lívingston in the cool morning light.",caution:"Izabal is a malaria-risk department; prioritize mosquito protection and ask a clinician about prevention."
  },
  {
    id:"chichi",name:"Chichicastenango",region:"Quiché",category:"Culture",mood:"Market day & living ritual",days:"1–2 days",budget:1,altitude:"1,965 m",coordinates:"14.9433° N",
    intro:"Highland market energy, Maya ceremonial traditions and a town best understood beyond souvenir stalls.",history:"Known locally as Chichi, the town is a major K’iche’ Maya cultural center. The Popol Vuh manuscript was recorded nearby, and Catholic and Maya practices visibly coexist around Santo Tomás church.",bestFor:["Markets","Textiles","Culture","Day trips"],color:"gold",
    activities:[m("Thursday/Sunday market","Arrive early; browse produce and household sections as well as crafts.","3 hr"),m("Iglesia de Santo Tomás","Observe active ceremonies respectfully; avoid photographing worship without permission.","30 min"),m("Pascual Abaj","Hire a local guide to understand this sacred hill and its protocols.","1.5 hr"),m("Colorful cemetery","Walk with sensitivity; it is an active place of remembrance.","45 min")],eat:[m("Market comedores","Choose a busy stall for caldo, tamal or grilled meat.","Local"),m("Hotel Santo Tomás","Calm courtyard lunch away from the market crush.","Classic")],stay:[m("Hotel Santo Tomás","Historic central hotel with courtyards.","Classic"),m("Mayan Inn","Atmospheric old-school stay near the center.","Historic")],transport:[m("From Atitlán","Shared shuttle on market days; around 2.5–3 hours each way.","Shuttle"),m("From Antigua","Long day trip; an overnight makes the early market far calmer.","Road")],tip:"Sleep the night before a market day, visit produce aisles first, and ask before photographing people or ceremonies."
  },
  {
    id:"xela",name:"Quetzaltenango (Xela)",region:"Quetzaltenango",category:"Culture",mood:"Highland city, local rhythm",days:"3 days",budget:1,altitude:"2,330 m",coordinates:"14.8347° N",
    intro:"A cooler, less-touristed highland city for Spanish study, neoclassical streets and mountain day trips.",history:"Xela grew as a K’iche’ center and later a major coffee and commercial city. Its central architecture reflects the prosperity and ideals of the late 19th-century Liberal era.",bestFor:["Spanish study","Hot springs","Hiking","Local life"],color:"berry",
    activities:[m("Parque Centro América","Read the neoclassical city around its central plaza.","1 hr"),m("Fuentes Georginas","Forest hot springs above Zunil; go early on a weekday.","Half day"),m("Cerro El Baúl","Local hill walk and city viewpoint; ask your lodging about current safety.","2 hr"),m("San Francisco El Alto market","Huge Friday market known for textiles and livestock.","Half day"),m("Spanish school week","Xela is one of Guatemala’s strongest bases for immersive lessons.","5+ days")],eat:[m("Sabor de la India","Well-loved Indian kitchen near the center.","Casual"),m("Xelapan","Local bakery institution for bread and sweet treats.","Classic"),m("Mercado La Democracia","Market snacks, fruit and everyday lunch counters.","Local")],stay:[m("Casa Seibel","Characterful budget guesthouse in the center.","Value"),m("Latam Hotel Plaza Pradera","Modern full-service option outside the historic core.","Comfort")],transport:[m("From Lake Atitlán","Shuttle or bus via the Interamericana; allow 3–4 hours.","Road"),m("From Guatemala City","First-class coach or private shuttle by day.","Coach")],tip:"Stay long enough for the city to work on you. Xela is better as a learning base than a checklist stop."
  },
  {
    id:"guatemala-city",name:"Guatemala City",region:"Guatemala",category:"City",mood:"Museums, markets, modern kitchens",days:"2 days",budget:3,altitude:"1,500 m",coordinates:"14.6349° N",
    intro:"The capital rewards a planned approach: standout Maya collections, ambitious dining and distinct urban zones.",history:"The capital was established in the Ermita Valley after Antigua’s 1773 earthquakes. Today its cultural anchors span the historic center, museum district and modern Zona 4/10 neighborhoods.",bestFor:["Museums","Dining","Design","Connections"],color:"navy",
    activities:[m("Museo Popol Vuh","Excellent pre-Hispanic and colonial collection; check university access hours.","2 hr"),m("Museo Ixchel","Textiles and dress traditions from Maya communities across Guatemala.","2 hr"),m("Mapa en Relieve","Remarkable early-20th-century relief map in Parque Minerva.","1 hr"),m("Centro Histórico","National Palace exterior, cathedral and Sixth Avenue by day.","Half day"),m("4° Norte","Walkable creative district for cafés, design and evening dining.","2–3 hr")],eat:[m("Mercado Central","Basement comedores for pepián, jocón and everyday plates.","Local"),m("Mercado 24","Contemporary Guatemalan tasting menu.","Splurge"),m("Sublime","Modern tasting experience centered on Guatemalan ingredients.","Splurge")],stay:[m("Good Hotel Guatemala City","Design-forward social-impact stay in Zona 4.","Midrange"),m("Hyatt Centric Guatemala City","Reliable base in Zona 10.","Comfort"),m("Barceló Guatemala City","Airport-convenient full-service option.","Classic")],transport:[m("Airport to Zona 10/4","Use hotel transfer, vetted taxi or rideshare; avoid street-hailed white taxis.","Local"),m("To Antigua","Pre-booked shuttle or driver; traffic makes timing variable.","Road")],tip:"Group sights by zone and use trusted door-to-door transport between them rather than wandering across districts.",caution:"Check current neighborhood guidance. Avoid Zone 18 and Villa Nueva; use vetted transport, especially after dark."
  },
  {
    id:"paredon",name:"El Paredón",region:"Escuintla",category:"Coast",mood:"Black sand & slow surf",days:"2–3 days",budget:2,altitude:"Sea level",coordinates:"13.9173° N",
    intro:"A small Pacific surf town backed by mangroves, with dramatic black sand and a social traveler scene.",history:"El Paredón developed from a fishing community beside the Sipacate–Naranjo wetlands. Tourism now centers on surf and mangrove ecology; choose locally rooted operators.",bestFor:["Surf","Sunsets","Mangroves","Rest"],color:"sun",
    activities:[m("Beginner surf lesson","Book a morning lesson before wind and heat build.","2 hr"),m("Mangrove paddle","Go with a community guide at tide-appropriate hours.","2–3 hr"),m("Turtle conservation visit","Seasonal; choose programs that follow wildlife-handling standards.","Seasonal"),m("Black-sand sunset","The shore break is powerful—admire it from a safe distance.","1 hr")],eat:[m("Soul Food Kitchen","Casual traveler favorite for bowls and shared plates.","Casual"),m("Local fish comedores","Ask what came in that morning and support family kitchens.","Local")],stay:[m("Swell","Design-led surf stay with a quieter feel.","Boutique"),m("Mellow Hostel","Social beachfront option.","Social"),m("Casa Zala","Small, relaxed lodging near the beach.","Midrange")],transport:[m("From Antigua","Shared surf shuttle, usually 2.5–3.5 hours.","Shuttle"),m("Around town","Walk; roads are sandy and services are compact.","Local")],tip:"Plan activity at sunrise and late afternoon. Midday heat is for shade, a book and a long lunch.",caution:"Pacific currents and shore break can be dangerous. Swim only where current local advice says conditions are safe."
  },
  {
    id:"coban",name:"Cobán & Verapaces",region:"Alta Verapaz",category:"Nature",mood:"Cloud forest & cardamom",days:"3 days",budget:2,altitude:"1,320 m",coordinates:"15.4708° N",
    intro:"A misty highland base for caves, orchids, coffee and some of Guatemala’s richest protected landscapes.",history:"Cobán’s Q’eqchi’ Maya identity sits alongside a 19th-century coffee history shaped by German settlers. The region is renowned for cardamom, orchids and cloud forest.",bestFor:["Birding","Caves","Coffee","Waterfalls"],color:"forest",
    activities:[m("Orquigonia","Conservation-focused orchid reserve with guided forest walks.","2 hr"),m("Biotopo del Quetzal","Cloud-forest trails; dawn offers the best birding chance.","Half day"),m("Grutas del Rey Marcos","Cave system near San Juan Chamelco with local guides.","Half day"),m("Coffee/cardamom experience","Arrange through a vetted community or estate operator.","Half day")],eat:[m("Casa de la Crepe","Long-running Cobán café and restaurant.","Casual"),m("Kardamomuss","Regional and international dishes highlighting local spice.","Local flavor")],stay:[m("Casa Gaia","Green hillside hotel outside the center.","Quiet"),m("Park Hotel","Established full-service base near Cobán.","Classic")],transport:[m("From Guatemala City","Daytime shuttle or bus; allow 5–6 hours depending on works and traffic.","Road"),m("To Semuc Champey","Continue via Lanquín on slow mountain roads.","Road")],tip:"Use Cobán as a two-night nature base rather than only a lunch stop on the long road to Semuc.",caution:"Alta Verapaz is a malaria-risk department; discuss protection with a clinician."
  },
  {
    id:"huehue",name:"Huehuetenango Highlands",region:"Huehuetenango",category:"Offbeat",mood:"Remote ridges & blue water",days:"4+ days",budget:2,altitude:"1,900–3,800 m",coordinates:"15.3199° N",
    intro:"Guatemala at its most remote: Cuchumatanes plateaus, Maya towns and startling highland lagoons.",history:"The Cuchumatanes hold Guatemala’s highest non-volcanic terrain and diverse Mam, Q’anjob’al and other Maya communities. Travel here demands time, local knowledge and humility.",bestFor:["Remote landscapes","Culture","Trekking","Road trips"],color:"ice",
    activities:[m("Todos Santos Cuchumatán","Mam Maya town and gateway to high plateau walks.","1–2 days"),m("Laguna Brava","Remote turquoise lake requiring a community-guided 4x4 journey and hike.","2 days"),m("Juan Diéguez Olaverri viewpoint","Roadside panorama over the Cuchumatanes.","30 min"),m("Chiantla & Zaculeu","Highland town and compact Mam archaeological site near Huehue city.","Half day")],eat:[m("Huehue central market","Regional soups, tortillas and everyday highland food.","Local"),m("Community homestay meals","Arrange ahead with a responsible local guide.","Community")],stay:[m("Huehuetenango city hotel","Use the departmental capital as the logistics base.","Base"),m("Community lodging","Basic stays near remote sites; confirm bedding and meals.","Remote")],transport:[m("From Guatemala City/Xela","Private vehicle or established daytime coach; distances are slow.","Road"),m("Remote lagoons","High-clearance 4x4 and local guide are essential.","4x4")],tip:"Do not improvise this region. Build the trip around a reputable Huehuetenango-based guide and buffer days.",caution:"The current U.S. advisory says do not travel to Huehuetenango Department. Review your government’s advice and local conditions before including it."
  },
  {
    id:"quirigua",name:"Quiriguá",region:"Izabal",category:"History",mood:"Maya sculpture in the banana lowlands",days:"Half day",budget:1,altitude:"75 m",coordinates:"15.2706° N",
    intro:"A compact UNESCO Maya site holding some of the ancient Americas’ tallest and finest carved stelae.",history:"Quiriguá controlled an important Motagua River trade route and rose after defeating Copán in 738 CE. Its rulers recorded that power in immense sandstone monuments.",bestFor:["Archaeology","Road stops","Sculpture","History"],color:"clay",
    activities:[m("Great Plaza stelae","Read the monuments under their protective shelters; a guide adds crucial context.","1.5 hr"),m("Acropolis","Walk the quieter palace complex beyond the main field.","45 min"),m("Banana landscape","Notice how the archaeological park sits within the modern agricultural valley.","Drive")],eat:[m("Los Amates stop","Choose a busy roadside comedor for lunch rather than relying on site snacks.","Local")],stay:[m("Río Dulce","The most appealing nearby overnight base, about 1–1.5 hours away.","Recommended"),m("Los Amates","Basic practical lodging if breaking a road journey.","Simple")],transport:[m("Guatemala City–Río Dulce road","Quiriguá is a worthwhile planned stop near Los Amates.","Road"),m("From Copán, Honduras","Possible cross-border pairing; verify current border hours and requirements.","Border")],tip:"Allow two hours with a guide. Quiriguá’s power is in carved detail and historical context, not monumental architecture."
  },
  {
    id:"pacaya",name:"Pacaya & Amatitlán",region:"Escuintla",category:"Adventure",mood:"Volcanic earth close to the capital",days:"1 day",budget:2,altitude:"2,552 m",coordinates:"14.3810° N",
    intro:"A popular guided volcano outing through dark lava landscapes, easily paired with Antigua or the capital.",history:"Pacaya is an active complex that has erupted frequently in recent decades. Routes and safe viewpoints change with volcanic activity, so local authority guidance is decisive.",bestFor:["Day hikes","Geology","Families","Short trips"],color:"ember",
    activities:[m("Authorized Pacaya trail","Guided hike to currently permitted viewpoints—not the active cone.","3–5 hr"),m("Lava-field geology","See recent flows where authorities allow access.","On trail"),m("Lake Amatitlán viewpoint","Stop for a broader look at the volcanic basin.","30 min")],eat:[m("San Francisco de Sales","Simple local food near the trailhead; carry your own water.","Local"),m("Antigua dinner","Return for a broader choice after the hike.","After hike")],stay:[m("Antigua","Best base for atmosphere and tour departures.","Base"),m("Guatemala City","Practical if flying the next day.","Transit")],transport:[m("From Antigua","Guided half-day tours include trailhead transfer.","Tour"),m("From Guatemala City","Private driver or guided pickup; avoid late return by road.","Road")],tip:"Treat Pacaya as an active-volcano visit, not a lava-photo promise. What you see depends entirely on safe access that day.",caution:"Pacaya is active. Follow CONRED/INSIVUMEH and park instructions; never enter restricted areas."
  }
];

export const phrases = [
  ["Basics",[["Hola / Buen día","Hello / Good morning"],["Por favor / Gracias","Please / Thank you"],["Disculpe","Excuse me"],["No entiendo","I don’t understand"],["¿Habla inglés?","Do you speak English?"],["Más despacio, por favor","More slowly, please"]]],
  ["Getting around",[["¿Dónde está…?","Where is…?"],["¿Cuánto cuesta?","How much does it cost?"],["¿A qué hora sale?","What time does it leave?"],["¿Este bus va a…?","Does this bus go to…?"],["Quisiera ir a…","I would like to go to…"],["¿Me avisa cuando lleguemos?","Can you tell me when we arrive?"]]],
  ["Food",[["Una mesa para dos","A table for two"],["¿Qué me recomienda?","What do you recommend?"],["Sin picante, por favor","Not spicy, please"],["Soy vegetariano/a","I’m vegetarian"],["La cuenta, por favor","The bill, please"],["Agua purificada","Purified water"]]],
  ["Safety & health",[["Necesito ayuda","I need help"],["¿Dónde hay una farmacia?","Where is a pharmacy?"],["Llame a una ambulancia","Call an ambulance"],["Estoy perdido/a","I’m lost"],["Tengo una alergia","I have an allergy"],["¿Es seguro caminar por aquí?","Is it safe to walk here?"]]],
  ["Warm connections",[["Mucho gusto","Nice to meet you"],["Qué bonito","How beautiful"],["¿Puedo tomar una foto?","May I take a photo?"],["Con permiso","May I pass?"],["Que le vaya bien","Have a good day"],["Matyox","Thank you in Kaqchikel"]]]
] as const;

export const faqs = [
  {q:"When is the best time to visit Guatemala?",a:"November through April is generally drier and easier for hiking. May through October is greener, with frequent afternoon rain and a higher risk of flooding or landslides; June–November is Atlantic hurricane season. Semana Santa is spectacular but requires very early booking."},
  {q:"Do I need a visa or entry form?",a:"Requirements depend on nationality. U.S. citizens generally do not need a tourist visa for stays up to 90 days, but Guatemala requires an electronic immigration/customs declaration for entry and exit. Verify with Guatemala’s immigration authority or your nearest embassy before travel."},
  {q:"Is Guatemala safe for independent travelers?",a:"Risk varies significantly by location. The U.S. State Department currently lists Guatemala at Level 3 and advises against travel to San Marcos, Huehuetenango, Zone 18 of Guatemala City and Villa Nueva. Use vetted shuttles, hotel taxis or rideshare; avoid public buses and isolated hikes; check your own government’s current advice."},
  {q:"Can I drink the tap water?",a:"Do not assume tap water is safe. Use sealed or reliably filtered/purified water, including for brushing teeth when your lodging advises it. Choose busy food stalls and use normal hand hygiene."},
  {q:"What vaccines or medicines should I discuss?",a:"CDC recommends routine vaccines be current and commonly recommends hepatitis A; other advice depends on age and trip style. Malaria medication may be recommended for Alta/Baja Verapaz, Escuintla, Izabal and Petén, while Antigua, Guatemala City and Lake Atitlán are not malaria transmission areas. Consult a travel clinician for your exact route."},
  {q:"How should I travel between destinations?",a:"Tourist shuttles are practical on the Antigua–Atitlán–Xela corridor. Domestic flights save time between Guatemala City and Flores. Use daytime first-class coaches or private drivers on longer routes; night road travel and local ‘chicken buses’ carry higher crash and crime risk."},
  {q:"How does money work?",a:"The currency is the Guatemalan quetzal (GTQ). Carry smaller notes for markets, boats and rural areas. Use ATMs inside banks or secure commercial locations, decline dynamic currency conversion, and keep a second card separately."},
  {q:"Do I need a guide for volcanoes?",a:"Yes. CONRED recommends checking weather and volcanic bulletins, notifying local authorities and using an authorized local guide. Never hike active restricted cones such as Fuego or Santiaguito; access around Acatenango and Pacaya can change quickly."},
  {q:"Can I cross into Belize, Honduras, El Salvador or Mexico?",a:"Overland routes are common, but entry rules, fees, schedules and security conditions change. Use established international operators, travel by day, and verify requirements for every passport and border shortly before departure."},
  {q:"How much time should I allow?",a:"For a first trip, 10–14 days covers Antigua, Atitlán and Petén without constant transit. Add Semuc only with at least three extra days; add Río Dulce/Lívingston with another three. Guatemala’s road distances routinely take longer than the map suggests."}
];

export const sources = [
  ["Guatemala travel advisory","https://travel.state.gov/en/international-travel/travel-advisories/guatemala.html"],
  ["CDC traveler health","https://wwwnc.cdc.gov/travel/destinations/traveler/none/guatemala/"],
  ["CONRED volcano guidance","https://conred.gob.gt/aventura-con-prevencion-recomendaciones-para-ascenso-a-volcanes/"],
  ["INGUAT tourism guides","https://inguat.gob.gt/"],
] as const;
